"""create parcels

Revision ID: c1bcc70b6c65
Revises:
Create Date: 2025-12-17 20:26:46.747986

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c1bcc70b6c65"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "parcel_types",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_parcel_types_id"), "parcel_types", ["id"], unique=False)
    op.create_table(
        "parcels",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("session_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=225), nullable=False),
        sa.Column("weight", sa.Numeric(precision=10, scale=3), nullable=False),
        sa.Column("parcel_type_id", sa.Integer(), nullable=False),
        sa.Column(
            "declared_value_usd", sa.Numeric(precision=12, scale=2), nullable=False
        ),
        sa.Column(
            "delivery_cost_rub", sa.Numeric(precision=12, scale=2), nullable=True
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("tracking_code", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["parcel_type_id"],
            ["parcel_types.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tracking_code"),
    )
    op.create_index(
        op.f("ix_parcels_delivery_cost_rub"),
        "parcels",
        ["delivery_cost_rub"],
        unique=False,
    )
    op.create_index(
        op.f("ix_parcels_parcel_type_id"), "parcels", ["parcel_type_id"], unique=False
    )
    op.create_index(
        op.f("ix_parcels_session_id"), "parcels", ["session_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_parcels_session_id"), table_name="parcels")
    op.drop_index(op.f("ix_parcels_parcel_type_id"), table_name="parcels")
    op.drop_index(op.f("ix_parcels_delivery_cost_rub"), table_name="parcels")
    op.drop_table("parcels")
    op.drop_index(op.f("ix_parcel_types_id"), table_name="parcel_types")
    op.drop_table("parcel_types")
    # ### end Alembic commands ###
